name: uv.lock check

on:
  pull_request:
    paths:
      - '**/pyproject.toml'
      - 'uv.lock'

jobs:
  uv-lock-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build helper image with uv
        run: |
          cat > docker-uv-helper.Dockerfile <<'DOCKERFILE'
          FROM python:3.12
          COPY --from=ghcr.io/astral-sh/uv:0.8 /uv /uvx /bin/
          WORKDIR /app
          ENTRYPOINT ["/bin/sh","-c"]
          DOCKERFILE
          docker build -f docker-uv-helper.Dockerfile -t uv-helper:0.8 .

      - name: Run uv lock --check
        run: |
          docker run --rm -v "$GITHUB_WORKSPACE:/app" -w /app uv-helper:0.8 /bin/uv lock --check

      - name: Show uv.lock diff (for debugging)
        if: failure()
        run: |
          echo '--- uv.lock ---'
          sed -n '1,200p' uv.lock || true
